export const TYPE_COLORS: { [key: string]: string } = {
    normal: "#A8A77A",
    fire: "#EE8130",
    water: "#6390F0",
    grass: "#7AC74C",
    flying: "#A98FF3",
    fighting: "#C22E28",
    poison: "#A33EA1",
    electric: "#F7D02C",
    ground: "#E2BF65",
    rock: "#B6A136",
    psychic: "#F95587",
    ice: "#96D9D6",
    bug: "#A6B91A",
    ghost: "#735797",
    steel: "#B7B7CE",
    dragon: "#6F35FC",
    dark: "#705746",
    fairy: "#D685AD",
} as const;

export const TYPE_KO: { [key: string]: string } = {
    normal: "노말",
    fire: "불꽃",
    water: "물",
    grass: "풀",
    flying: "비행",
    fighting: "격투",
    poison: "독",
    electric: "전기",
    ground: "땅",
    rock: "바위",
    psychic: "에스퍼",
    ice: "얼음",
    bug: "벌레",
    ghost: "고스트",
    steel: "강철",
    dragon: "드래곤",
    dark: "악",
    fairy: "페어리",
} as const;

export const VERSION_KO: { [key: string]: string } = {
    x: "X",
    y: "Y",
    "omega-ruby": "오메가 루비",
    "alpha-sapphire": "알파 사파이어",
    sun: "썬",
    moon: "문",
    "ultra-sun": "울트라 썬",
    "ultra-moon": "울트라 문",
    "lets-go-pikachu": "렛츠고 피카쥬",
    "lets-go-eevee": "렛츠고 이브이",
    sword: "소드",
    shield: "실드",
} as const;

export const REGION_KO: { [key: string]: string } = {
    kanto: "관동",
    johto: "성도",
    hoenn: "호연",
    sinnoh: "신오",
    unova: "하나",
    kalos: "칼로스",
    alola: "알로라",
    galar: "가라르",
    paldea: "팔데아",
} as const;

export const REGION_NUM: { [key: string]: string } = {
    kanto: "1",
    johto: "2",
    hoenn: "3",
    sinnoh: "4",
    unova: "5",
    kalos: "6",
    alola: "7",
    galar: "8",
    paldea: "9",
} as const;